version: '2'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bitSpeed 
    volumes:
      - persistent:/var/lib/mysql
    networks:
      - app-tier
  myapp:
    build: .
    restart: always
    volumes:
      - ./:/app
    ports:
      - 4000:4000
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bitSpeed
      - MYSQL_HOST=db
    depends_on:
      - db
    networks:
      - app-tier

volumes:
  persistent:
networks:
  app-tier:
    driver: bridge
